networks:
  numeris-test:

services:
  postgres:
    image: postgres:12.20-alpine
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=nelwhix
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=numeris_test
    ports:
      - "5432:5432"
    networks:
      - numeris-test
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - numeris-test

volumes:
  postgres_data:
    driver: local